import fs from "fs";
import path from "path";

const countries: [string, string, string, string][] = [
  ["af", "Afghanistan", "Kabul", "Asia"],
  ["al", "Albania", "Tirana", "Europa"],
  ["dz", "Algeria", "Algeri", "Africa"],
  ["ad", "Andorra", "Andorra la Vella", "Europa"],
  ["ao", "Angola", "Luanda", "Africa"],
  ["ag", "Antigua e Barbuda", "Saint John's", "America del Nord"],
  ["sa", "Arabia Saudita", "Riyad", "Asia"],
  ["ar", "Argentina", "Buenos Aires", "America del Sud"],
  ["am", "Armenia", "Erevan", "Asia"],
  ["au", "Australia", "Canberra", "Oceania"],
  ["at", "Austria", "Vienna", "Europa"],
  ["az", "Azerbaigian", "Baku", "Asia"],
  ["bs", "Bahamas", "Nassau", "America del Nord"],
  ["bh", "Bahrein", "Manama", "Asia"],
  ["bd", "Bangladesh", "Dacca", "Asia"],
  ["bb", "Barbados", "Bridgetown", "America del Nord"],
  ["be", "Belgio", "Bruxelles", "Europa"],
  ["bz", "Belize", "Belmopan", "America del Nord"],
  ["bj", "Benin", "Porto-Novo", "Africa"],
  ["by", "Bielorussia", "Minsk", "Europa"],
  ["mm", "Birmania", "Naypyidaw", "Asia"],
  ["bo", "Bolivia", "Sucre", "America del Sud"],
  ["ba", "Bosnia ed Erzegovina", "Sarajevo", "Europa"],
  ["bw", "Botswana", "Gaborone", "Africa"],
  ["br", "Brasile", "Brasilia", "America del Sud"],
  ["bn", "Brunei", "Bandar Seri Begawan", "Asia"],
  ["bg", "Bulgaria", "Sofia", "Europa"],
  ["bf", "Burkina Faso", "Ouagadougou", "Africa"],
  ["bi", "Burundi", "Gitega", "Africa"],
  ["bt", "Bhutan", "Thimphu", "Asia"],
  ["kh", "Cambogia", "Phnom Penh", "Asia"],
  ["cm", "Camerun", "Yaoundé", "Africa"],
  ["ca", "Canada", "Ottawa", "America del Nord"],
  ["cv", "Capo Verde", "Praia", "Africa"],
  ["td", "Ciad", "N'Djamena", "Africa"],
  ["cl", "Cile", "Santiago", "America del Sud"],
  ["cn", "Cina", "Pechino", "Asia"],
  ["cy", "Cipro", "Nicosia", "Asia"],
  ["co", "Colombia", "Bogotà", "America del Sud"],
  ["km", "Comore", "Moroni", "Africa"],
  ["kp", "Corea del Nord", "Pyongyang", "Asia"],
  ["kr", "Corea del Sud", "Seul", "Asia"],
  ["ci", "Costa d'Avorio", "Yamoussoukro", "Africa"],
  ["cr", "Costa Rica", "San José", "America del Nord"],
  ["hr", "Croazia", "Zagabria", "Europa"],
  ["cu", "Cuba", "L'Avana", "America del Nord"],
  ["dk", "Danimarca", "Copenaghen", "Europa"],
  ["dm", "Dominica", "Roseau", "America del Nord"],
  ["ec", "Ecuador", "Quito", "America del Sud"],
  ["eg", "Egitto", "Il Cairo", "Africa"],
  ["sv", "El Salvador", "San Salvador", "America del Nord"],
  ["ae", "Emirati Arabi Uniti", "Abu Dhabi", "Asia"],
  ["er", "Eritrea", "Asmara", "Africa"],
  ["ee", "Estonia", "Tallinn", "Europa"],
  ["et", "Etiopia", "Addis Abeba", "Africa"],
  ["fj", "Figi", "Suva", "Oceania"],
  ["ph", "Filippine", "Manila", "Asia"],
  ["fi", "Finlandia", "Helsinki", "Europa"],
  ["fr", "Francia", "Parigi", "Europa"],
  ["ga", "Gabon", "Libreville", "Africa"],
  ["gm", "Gambia", "Banjul", "Africa"],
  ["ge", "Georgia", "Tbilisi", "Asia"],
  ["de", "Germania", "Berlino", "Europa"],
  ["gh", "Ghana", "Accra", "Africa"],
  ["jm", "Giamaica", "Kingston", "America del Nord"],
  ["jp", "Giappone", "Tokyo", "Asia"],
  ["dj", "Gibuti", "Gibuti", "Africa"],
  ["jo", "Giordania", "Amman", "Asia"],
  ["gr", "Grecia", "Atene", "Europa"],
  ["gd", "Grenada", "Saint George's", "America del Nord"],
  ["gt", "Guatemala", "Città del Guatemala", "America del Nord"],
  ["gn", "Guinea", "Conakry", "Africa"],
  ["gw", "Guinea-Bissau", "Bissau", "Africa"],
  ["gq", "Guinea Equatoriale", "Malabo", "Africa"],
  ["gy", "Guyana", "Georgetown", "America del Sud"],
  ["ht", "Haiti", "Port-au-Prince", "America del Nord"],
  ["hn", "Honduras", "Tegucigalpa", "America del Nord"],
  ["in", "India", "Nuova Delhi", "Asia"],
  ["id", "Indonesia", "Giacarta", "Asia"],
  ["ir", "Iran", "Teheran", "Asia"],
  ["iq", "Iraq", "Baghdad", "Asia"],
  ["ie", "Irlanda", "Dublino", "Europa"],
  ["is", "Islanda", "Reykjavik", "Europa"],
  ["il", "Israele", "Gerusalemme", "Asia"],
  ["it", "Italia", "Roma", "Europa"],
  ["kz", "Kazakistan", "Astana", "Asia"],
  ["ke", "Kenya", "Nairobi", "Africa"],
  ["kg", "Kirghizistan", "Bishkek", "Asia"],
  ["ki", "Kiribati", "Tarawa", "Oceania"],
  ["kw", "Kuwait", "Kuwait City", "Asia"],
  ["la", "Laos", "Vientiane", "Asia"],
  ["ls", "Lesotho", "Maseru", "Africa"],
  ["lv", "Lettonia", "Riga", "Europa"],
  ["lb", "Libano", "Beirut", "Asia"],
  ["lr", "Liberia", "Monrovia", "Africa"],
  ["ly", "Libia", "Tripoli", "Africa"],
  ["li", "Liechtenstein", "Vaduz", "Europa"],
  ["lt", "Lituania", "Vilnius", "Europa"],
  ["lu", "Lussemburgo", "Lussemburgo", "Europa"],
  ["mk", "Macedonia del Nord", "Skopje", "Europa"],
  ["mg", "Madagascar", "Antananarivo", "Africa"],
  ["mw", "Malawi", "Lilongwe", "Africa"],
  ["my", "Malaysia", "Kuala Lumpur", "Asia"],
  ["mv", "Maldive", "Malé", "Asia"],
  ["ml", "Mali", "Bamako", "Africa"],
  ["mt", "Malta", "Valletta", "Europa"],
  ["ma", "Marocco", "Rabat", "Africa"],
  ["mh", "Isole Marshall", "Majuro", "Oceania"],
  ["mr", "Mauritania", "Nouakchott", "Africa"],
  ["mu", "Mauritius", "Port Louis", "Africa"],
  ["mx", "Messico", "Città del Messico", "America del Nord"],
  ["fm", "Micronesia", "Palikir", "Oceania"],
  ["md", "Moldavia", "Chișinău", "Europa"],
  ["mc", "Monaco", "Monaco", "Europa"],
  ["mn", "Mongolia", "Ulan Bator", "Asia"],
  ["me", "Montenegro", "Podgorica", "Europa"],
  ["mz", "Mozambico", "Maputo", "Africa"],
  ["na", "Namibia", "Windhoek", "Africa"],
  ["nr", "Nauru", "Yaren", "Oceania"],
  ["np", "Nepal", "Katmandu", "Asia"],
  ["ni", "Nicaragua", "Managua", "America del Nord"],
  ["ne", "Niger", "Niamey", "Africa"],
  ["ng", "Nigeria", "Abuja", "Africa"],
  ["no", "Norvegia", "Oslo", "Europa"],
  ["nz", "Nuova Zelanda", "Wellington", "Oceania"],
  ["om", "Oman", "Mascate", "Asia"],
  ["nl", "Paesi Bassi", "Amsterdam", "Europa"],
  ["pk", "Pakistan", "Islamabad", "Asia"],
  ["pw", "Palau", "Ngerulmud", "Oceania"],
  ["pa", "Panama", "Panama City", "America del Nord"],
  ["pg", "Papua Nuova Guinea", "Port Moresby", "Oceania"],
  ["py", "Paraguay", "Asunción", "America del Sud"],
  ["pe", "Perù", "Lima", "America del Sud"],
  ["pl", "Polonia", "Varsavia", "Europa"],
  ["pt", "Portogallo", "Lisbona", "Europa"],
  ["qa", "Qatar", "Doha", "Asia"],
  ["gb", "Regno Unito", "Londra", "Europa"],
  ["cd", "RD Congo", "Kinshasa", "Africa"],
  ["cz", "Rep. Ceca", "Praga", "Europa"],
  ["cf", "Rep. Centrafricana", "Bangui", "Africa"],
  ["cg", "Rep. del Congo", "Brazzaville", "Africa"],
  ["do", "Rep. Dominicana", "Santo Domingo", "America del Nord"],
  ["ro", "Romania", "Bucarest", "Europa"],
  ["rw", "Ruanda", "Kigali", "Africa"],
  ["ru", "Russia", "Mosca", "Europa"],
  ["kn", "Saint Kitts e Nevis", "Basseterre", "America del Nord"],
  ["lc", "Saint Lucia", "Castries", "America del Nord"],
  ["vc", "Saint Vincent e Grenadine", "Kingstown", "America del Nord"],
  ["ws", "Samoa", "Apia", "Oceania"],
  ["sm", "San Marino", "San Marino", "Europa"],
  ["st", "São Tomé e Príncipe", "São Tomé", "Africa"],
  ["sn", "Senegal", "Dakar", "Africa"],
  ["rs", "Serbia", "Belgrado", "Europa"],
  ["sc", "Seychelles", "Victoria", "Africa"],
  ["sl", "Sierra Leone", "Freetown", "Africa"],
  ["sg", "Singapore", "Singapore", "Asia"],
  ["sy", "Siria", "Damasco", "Asia"],
  ["sk", "Slovacchia", "Bratislava", "Europa"],
  ["si", "Slovenia", "Lubiana", "Europa"],
  ["so", "Somalia", "Mogadishu", "Africa"],
  ["es", "Spagna", "Madrid", "Europa"],
  ["lk", "Sri Lanka", "Sri Jayawardenepura Kotte", "Asia"],
  ["us", "Stati Uniti", "Washington D.C.", "America del Nord"],
  ["za", "Sudafrica", "Pretoria", "Africa"],
  ["sd", "Sudan", "Khartoum", "Africa"],
  ["ss", "Sudan del Sud", "Giuba", "Africa"],
  ["sr", "Suriname", "Paramaribo", "America del Sud"],
  ["se", "Svezia", "Stoccolma", "Europa"],
  ["ch", "Svizzera", "Berna", "Europa"],
  ["sz", "eSwatini", "Mbabane", "Africa"],
  ["tj", "Tagikistan", "Dušanbe", "Asia"],
  ["tz", "Tanzania", "Dodoma", "Africa"],
  ["th", "Thailandia", "Bangkok", "Asia"],
  ["tl", "Timor Est", "Dili", "Asia"],
  ["tg", "Togo", "Lomé", "Africa"],
  ["to", "Tonga", "Nuku'alofa", "Oceania"],
  ["tt", "Trinidad e Tobago", "Port of Spain", "America del Nord"],
  ["tn", "Tunisia", "Tunisi", "Africa"],
  ["tr", "Turchia", "Ankara", "Asia"],
  ["tm", "Turkmenistan", "Ashgabat", "Asia"],
  ["tv", "Tuvalu", "Funafuti", "Oceania"],
  ["ua", "Ucraina", "Kiev", "Europa"],
  ["ug", "Uganda", "Kampala", "Africa"],
  ["hu", "Ungheria", "Budapest", "Europa"],
  ["uy", "Uruguay", "Montevideo", "America del Sud"],
  ["uz", "Uzbekistan", "Tashkent", "Asia"],
  ["vu", "Vanuatu", "Port Vila", "Oceania"],
  ["va", "Vaticano", "Città del Vaticano", "Europa"],
  ["ve", "Venezuela", "Caracas", "America del Sud"],
  ["vn", "Vietnam", "Hanoi", "Asia"],
  ["ye", "Yemen", "Sana'a", "Asia"],
  ["zm", "Zambia", "Lusaka", "Africa"],
  ["zw", "Zimbabwe", "Harare", "Africa"],
  ["ps", "Palestina", "Ramallah", "Asia"],
  ["tw", "Taiwan", "Taipei", "Asia"],
  ["xk", "Kosovo", "Pristina", "Europa"],
];

const lines = countries.map(
  ([code, name, capital, continent]) =>
    `  { code: "${code}", name: ${JSON.stringify(name)}, capital: ${JSON.stringify(capital)}, continent: "${continent}" },`
);

const content = `export type Continent =
  | "Europa"
  | "Asia"
  | "Africa"
  | "America del Nord"
  | "America del Sud"
  | "Oceania";

export interface Country {
  code: string;
  name: string;
  capital: string;
  continent: Continent;
}

export const CONTINENTS: Continent[] = [
  "Europa",
  "Asia",
  "Africa",
  "America del Nord",
  "America del Sud",
  "Oceania",
];

export const COUNTRIES: Country[] = [
${lines.join("\n")}
];
`;

const out = path.join(process.cwd(), "src/data/countries.ts");
fs.writeFileSync(out, content);
console.log(`Written ${countries.length} countries to ${out}`);
